//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace labyrinthEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("labyrinthEditor.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Length of the map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AskHeight {
            get {
                return ResourceManager.GetString("AskHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width of the map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AskWidth {
            get {
                return ResourceManager.GetString("AskWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chamber に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Chamber {
            get {
                return ResourceManager.GetString("Chamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the absolute path to the map file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterAbsolutePath {
            get {
                return ResourceManager.GetString("EnterAbsolutePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the filename (without extension) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterFileName {
            get {
                return ResourceManager.GetString("EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the save path (or leave empty to save to the program&apos;s location) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterPathOrUseDefaultPath {
            get {
                return ResourceManager.GetString("EnterPathOrUseDefaultPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: Invalid filename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_InvalidFileName {
            get {
                return ResourceManager.GetString("Error_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: No chamber on the map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_NoChamber {
            get {
                return ResourceManager.GetString("Error_NoChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: This path doesn&apos;t exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_PathDoesntExist {
            get {
                return ResourceManager.GetString("Error_PathDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit from the map editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create new map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItemCreateMap {
            get {
                return ResourceManager.GetString("MenuItemCreateMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load map file into the editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItemLoadMap {
            get {
                return ResourceManager.GetString("MenuItemLoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Place chamber に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlaceChamber {
            get {
                return ResourceManager.GetString("PlaceChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press the enter key to continue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PressEnterToContinue {
            get {
                return ResourceManager.GetString("PressEnterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to the main menu  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReturnToTheMenu {
            get {
                return ResourceManager.GetString("ReturnToTheMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
