//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labyrinthEditor.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings_hu {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_hu() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("labyrinthEditor.Resources.strings_hu", typeof(strings_hu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        public static string MenuItemLoadMap {
            get {
                return ResourceManager.GetString("MenuItemLoadMap", resourceCulture);
            }
        }
        
        public static string MenuItemCreateMap {
            get {
                return ResourceManager.GetString("MenuItemCreateMap", resourceCulture);
            }
        }
        
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        public static string AskHeight {
            get {
                return ResourceManager.GetString("AskHeight", resourceCulture);
            }
        }
        
        public static string AskWidth {
            get {
                return ResourceManager.GetString("AskWidth", resourceCulture);
            }
        }
        
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
